[package]
name = "spenn-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = {version = "4" }
serde = { version = "1.0", features = ["derive"] }
env_logger = { version = "*" }
dotenv = { version = "*" }